import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    home: 'Home',
    products: 'Products',
    categories: 'Categories',
    adminLogin: 'Admin Login',
    dashboard: 'Dashboard',
    logout: 'Logout',
    orderWhatsApp: 'Order via WhatsApp',
    orderWhatsAppSub: 'Tap to chat with us on WhatsApp and place your order',
    view: 'View',
    quickView: 'Quick View',
    backToProducts: '← Back to Products',
    outOfStock: 'Out of Stock',
    inStock: 'in stock',
    description: 'Description',
    availability: 'Availability',
    sku: 'SKU',
    featuredProducts: 'Featured Products',
    handpicked: 'Handpicked For You',
    shopByCategory: 'Shop by Category',
    exploreRange: 'Explore Our Range',
    exploreCollection: 'Explore Collection',
    browseCategories: 'Browse Categories',
    viewAllProducts: 'View All Products',
    premiumSince: 'Premium Stationery Since 1995',
    heroTitle: 'Your Complete Stationery Store',
    heroSub: 'Discover our curated collection of premium stationery — from elegant pens to artisanal notebooks. Serving Bengaluru with love.',
    freeShipping: 'Free Delivery',
    freeShippingDesc: 'On orders above ₹500',
    premiumQuality: 'Premium Quality',
    premiumQualityDesc: 'Curated selections',
    giftWrapping: 'Gift Wrapping',
    giftWrappingDesc: 'Available on request',
    visitStore: 'Visit Store',
    visitStoreDesc: 'Bengaluru, Karnataka',
    ourStory: 'Our Story',
    aboutTitle: 'Quality Stationery, Trusted Since 1995',
    aboutP1: 'Kuldevi Stationery has been Bengaluru\'s trusted destination for premium writing instruments, artisanal notebooks, and office essentials for over 25 years.',
    aboutP2: 'Our carefully curated collection features timeless classics and modern innovations — making every visit a delight.',
    learnMore: 'Explore Our Products',
    ctaTitle: 'Looking for the Perfect Stationery?',
    ctaSub: 'Browse our collection and find pieces that inspire your creativity. Order via WhatsApp — simple and easy!',
    startBrowsing: 'Browse Products',
    quickLinks: 'Quick Links',
    contactUs: 'संपर्क करें',
    address: 'Kuldevi Stationery, Bengaluru, Karnataka - 560001',
    email: 'info@kuldevistationery.com',
    phone: '+91 98765 43210',
    copyright: 'Kuldevi Stationery. All rights reserved.',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    username: 'Username',
    password: 'Password',
    adminLoginTitle: 'Admin Login',
    invalidCreds: 'Invalid username or password',
    newProduct: 'Add New Product',
    loadingDash: 'Loading dashboard...',
    years: 'Years of Excellence',
  },
  hi: {
    home: 'होम',
    products: 'उत्पाद',
    categories: 'श्रेणियाँ',
    adminLogin: 'एडमिन लॉगिन',
    dashboard: 'डैशबोर्ड',
    logout: 'लॉगआउट',
    orderWhatsApp: 'व्हाट्सऐप पर ऑर्डर करें',
    orderWhatsAppSub: 'व्हाट्सऐप पर चैट करें और ऑर्डर दें',
    view: 'देखें',
    quickView: 'त्वरित देखें',
    backToProducts: '← उत्पादों पर वापस',
    outOfStock: 'स्टॉक में नहीं',
    inStock: 'स्टॉक में',
    description: 'विवरण',
    availability: 'उपलब्धता',
    sku: 'SKU',
    featuredProducts: 'विशेष उत्पाद',
    handpicked: 'आपके लिए चुने गए',
    shopByCategory: 'श्रेणी अनुसार देखें',
    exploreRange: 'हमारी विविधता देखें',
    exploreCollection: 'संग्रह देखें',
    browseCategories: 'श्रेणियाँ देखें',
    viewAllProducts: 'सभी उत्पाद देखें',
    premiumSince: '१९९५ से प्रीमियम स्टेशनरी',
    heroTitle: 'आपकी पूरी स्टेशनरी दुकान',
    heroSub: 'उत्कृष्ट पेन, नोटबुक और कार्यालय सामग्री का संग्रह। बेंगलुरु में आपकी अपनी दुकान।',
    freeShipping: 'मुफ़्त डिलीवरी',
    freeShippingDesc: '₹५०० से ऊपर के ऑर्डर पर',
    premiumQuality: 'उत्कृष्ट गुणवत्ता',
    premiumQualityDesc: 'चुनी हुई वस्तुएं',
    giftWrapping: 'गिफ़्ट पैकिंग',
    giftWrappingDesc: 'अनुरोध पर उपलब्ध',
    visitStore: 'दुकान पर आएं',
    visitStoreDesc: 'बेंगलुरु, कर्नाटक',
    ourStory: 'हमारी कहानी',
    aboutTitle: 'गुणवत्ता की स्टेशनरी, १९९५ से विश्वसनीय',
    aboutP1: 'कुलदेवी स्टेशनरी — बेंगलुरु की भरोसेमंद स्टेशनरी दुकान। २५ से अधिक वर्षों से उत्तम लेखन सामग्री, नोटबुक और ऑफिस का सामान प्रदान कर रहे हैं।',
    aboutP2: 'हमारे संग्रह में क्लासिक और आधुनिक दोनों तरह की वस्तुएं हैं — हर बार कुछ नया मिलेगा।',
    learnMore: 'उत्पाद देखें',
    ctaTitle: 'सही स्टेशनरी ढूंढ रहे हैं?',
    ctaSub: 'हमारा संग्रह देखें और अपनी पसंद चुनें। व्हाट्सऐप पर ऑर्डर करें — बिल्कुल आसान!',
    startBrowsing: 'उत्पाद देखें',
    quickLinks: 'त्वरित लिंक',
    contactUs: 'संपर्क करें',
    address: 'कुलदेवी स्टेशनरी, बेंगलुरु, कर्नाटक - ५६०००१',
    email: 'info@kuldevistationery.com',
    phone: '+91 98765 43210',
    copyright: 'कुलदेवी स्टेशनरी। सर्वाधिकार सुरक्षित।',
    signingIn: 'लॉगिन हो रहा है...',
    signIn: 'लॉगिन करें',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    adminLoginTitle: 'एडमिन लॉगिन',
    invalidCreds: 'गलत उपयोगकर्ता नाम या पासवर्ड',
    newProduct: 'नया उत्पाद जोड़ें',
    loadingDash: 'डैशबोर्ड लोड हो रहा है...',
    years: 'वर्षों की उत्कृष्टता',
  }
}

const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = (key) => translations[lang][key] ?? translations.en[key] ?? key
  const toggle = () => setLang(l => l === 'en' ? 'hi' : 'en')
  return (
    <LangContext.Provider value={{ lang, t, toggle }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
